{ pkgs, inputs ? {}, ... }:

let
  nixpkgsArchi = 
    if inputs ? archi-nixpkgs then
      inputs.archi-nixpkgs
    else
      (import (pkgs.fetchTarball "https://github.com/NixOS/nixpkgs/archive/b347d1435a65f95f3e23dc74f0cc1e30af8a4e9a.tar.gz") {});
  
  sources = pkgs.callPackage ../_sources/generated.nix { };
in
(import "${nixpkgsArchi}/pkgs/by-name/ar/archi/package.nix" {
  inherit (pkgs) lib stdenv fetchurl autoPatchelfHook makeWrapper jdk libsecret glib webkitgtk_4_1 wrapGAppsHook3 copyDesktopItems makeDesktopItem _7zz;
  
  # Provide nixosTests - normally from ${nixpkgs}/nixos/tests/archi.nix but not needed for home-manager
  nixosTests = { archi = null; };
}).overrideAttrs (old: {
  version = sources.archi.version;
  
  src = sources.archi.src;
  
  nativeBuildInputs = (old.nativeBuildInputs or []) ++ [ pkgs.adwaita-icon-theme pkgs.hicolor-icon-theme ];
  
  postInstall = (old.postInstall or "") + ''
    # Re-wrap Archi with theme environment variables
    rm -f $out/bin/Archi
    makeWrapper $out/libexec/Archi $out/bin/Archi \
      --prefix LD_LIBRARY_PATH : ${pkgs.lib.makeLibraryPath [ pkgs.glib pkgs.webkitgtk_4_1 ]} \
      --set WEBKIT_DISABLE_DMABUF_RENDERER 1 \
      --set GTK_THEME adwaita \
      --set XDG_CURRENT_DESKTOP GNOME \
      --prefix PATH : ${pkgs.jdk}/bin \
      --prefix XDG_DATA_DIRS : "${pkgs.adwaita-icon-theme}/share:${pkgs.hicolor-icon-theme}/share"
  '';

  postFixup = (old.postFixup or "") + ''
    # Fix the desktop file to use an absolute path to the bundled PNG icon
    # This must run in postFixup to ensure the desktop file has already been generated by copyDesktopItemsHook
    icon_path=$(find $out/libexec -name "app-64.png" | head -n 1)
    if [ -n "$icon_path" ] && [ -f "$out/share/applications/archi.desktop" ]; then
      sed -i 's|^Icon=.*|Icon='"$icon_path"'|' "$out/share/applications/archi.desktop"
    fi
  '';
  
  dontWrapGApps = false;
  
  passthru = (old.passthru or {}) // { 
    tests = { archi = null; };
  };
})
