# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  nuvio-desktop = {
    pname = "nuvio-desktop";
    version = "0.1.6-alpha";
    src = fetchurl {
      url = "https://github.com/aelrased/NuvioDesktop/releases/download/v0.1.6-alpha/Nuvio-0.1.6-alpha-x86_64.AppImage";
      sha256 = "sha256-d0locyV07BmJfxAEI8h8D3O4/YUEyqBMWZVS7q5k/5U=";
    };
  };
}
