# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0dd89124-dba9-42bc-8dca-124fc1b5cde3";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."luks-0dd89124-dba9-42bc-8dca-124fc1b5cde3".device = "/dev/disk/by-uuid/0dd89124-dba9-42bc-8dca-124fc1b5cde3";

  fileSystems."/srv" =
    { device = "/dev/mapper/luks-0dd89124-dba9-42bc-8dca-124fc1b5cde3";
      fsType = "btrfs";
      options = [ "subvol=@srv" ];
    };

  fileSystems."/root" =
    { device = "/dev/mapper/luks-0dd89124-dba9-42bc-8dca-124fc1b5cde3";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-0dd89124-dba9-42bc-8dca-124fc1b5cde3";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/mapper/luks-0dd89124-dba9-42bc-8dca-124fc1b5cde3";
      fsType = "btrfs";
      options = [ "subvol=@cache" ];
    };

  fileSystems."/var/tmp" =
    { device = "/dev/mapper/luks-0dd89124-dba9-42bc-8dca-124fc1b5cde3";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/mapper/luks-0dd89124-dba9-42bc-8dca-124fc1b5cde3";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/985C-967A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.npu.enable = true;
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}