services:
  syncio:
    image: ghcr.io/iamneur0/syncio:public
    restart: always
    env_file:
      - stack.env
    depends_on:
      - db
      - redis
    ports:
      - "3003:3000"
      - "4000:4000"

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: syncio
      POSTGRES_PASSWORD: syncio
      POSTGRES_DB: syncio
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data

volumes:
  pgdata:
  redis_data: