services:
  grayjay:
    image: grayjay
    container_name: ${CONTAINER_NAME}
    working_dir: ${WORKDIR}
    volumes:
      - grayjay_data:${DATA_DIR}
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - PORTFILE_PATH=${PORTFILE_PATH}
      - DATA_DIR=${DATA_DIR}
      - GRAYJAY_DIR=${GRAYJAY_DIR}
      - WORKDIR=${WORKDIR}
      - DISPLAY=:99
    security_opt:
      - seccomp:unconfined
    shm_size: '2gb'

volumes:
  grayjay_data:
