# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  angr-management = {
    pname = "angr-management";
    version = "v9.2.222";
    src = fetchurl {
      url = "https://github.com/angr/angr-management/releases/download/v9.2.222/angr-management-v9.2.222-x86_64.AppImage";
      sha256 = "sha256-ftXvNSMK+HdcTUSwBrcQUUfdDSinyi/p9s2V8dmO4HA=";
    };
  };
  apk-mitm = {
    pname = "apk-mitm";
    version = "v1.3.0";
    src = fetchFromGitHub {
      owner = "niklashigi";
      repo = "apk-mitm";
      rev = "v1.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-wcLShZ7O20i0hzz957dNmfjvxCn5lmWObTdTRF7p+I8=";
    };
  };
  archi = {
    pname = "archi";
    version = "5.9.0";
    src = fetchurl {
      url = "https://github.com/archimatetool/archi.io/releases/download/5.9.0/Archi-Linux64-5.9.0.tgz";
      sha256 = "sha256-0/3/EZw5upB0dvyhS0sfKqp7C4tc6vGDW+O9WU5iTc8=";
    };
  };
  ctfd-parser = {
    pname = "ctfd-parser";
    version = "1.1";
    src = fetchFromGitHub {
      owner = "p0dalirius";
      repo = "ctfd-parser";
      rev = "1.1";
      fetchSubmodules = false;
      sha256 = "sha256-2Rbe97xz48r22X61jjnwFPBiN0dIeUKd4zcSJxBrSd0=";
    };
  };
  dnspy = {
    pname = "dnspy";
    version = "6.6.0";
    src = fetchurl {
      url = "https://github.com/dnSpyEx/dnSpy/releases/download/v6.6.0/dnSpy-netframework.zip";
      sha256 = "sha256-Lq239JMa0YgtEEd89XGF0ojKzG46v5lY565zwKDzHdE=";
    };
  };
  ese-database-view = {
    pname = "ese-database-view";
    version = "1.79";
    src = fetchurl {
      url = "https://www.nirsoft.net/utils/esedatabaseview.zip";
      sha256 = "sha256-tjbPXj7aom6tJE9YxK43LJoopQXRego6btTc5BusOr8=";
    };
  };
  evolve = {
    pname = "evolve";
    version = "v1.6";
    src = fetchFromGitHub {
      owner = "JamesHabben";
      repo = "evolve";
      rev = "v1.6";
      fetchSubmodules = false;
      sha256 = "sha256-IRO2pqRK3pMqv49T4U/aAccilIA9pdVURFTlSeXy5D4=";
    };
  };
  ida-chat-plugin = {
    pname = "ida-chat-plugin";
    version = "883f9b3550725d81eed80c25dd28c75b320f22c7";
    src = fetchFromGitHub {
      owner = "HexRaysSA";
      repo = "ida-chat-plugin";
      rev = "883f9b3550725d81eed80c25dd28c75b320f22c7";
      fetchSubmodules = false;
      sha256 = "sha256-ueGelV0KZhE4k7O5VsBTSfZgWz/gm9Lr3CdIYl99Yd8=";
    };
    date = "2026-04-20";
  };
  libesedb = {
    pname = "libesedb";
    version = "7b35fcc8621de83ea0e5b9d4a503fda87ec02114";
    src = fetchgit {
      url = "https://github.com/libyal/libesedb.git";
      rev = "7b35fcc8621de83ea0e5b9d4a503fda87ec02114";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PTC+/HShcBGsTlsP7XwAUxHiNiBrTKENAA986awl3ME=";
    };
    date = "2026-06-25";
  };
  libfsntfs = {
    pname = "libfsntfs";
    version = "ff95361c7812ee43bb6503fdd6d0c4b7958db3b9";
    src = fetchgit {
      url = "https://github.com/libyal/libfsntfs.git";
      rev = "ff95361c7812ee43bb6503fdd6d0c4b7958db3b9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Q7e1l21asDiAI9PLcwFZktkf6PTxkXLFIeCZbkSNPQ0=";
    };
    date = "2026-06-26";
  };
  registry-spy = {
    pname = "registry-spy";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "andyjsmith";
      repo = "Registry-Spy";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-5D6uDjcCFGtkAyMp0S3blwc5vMP39dyKWTM+nocSIm0=";
    };
  };
  rem = {
    pname = "rem";
    version = "1.4.0";
    src = fetchurl {
      url = "https://github.com/liriliri/rem/releases/download/v1.4.0/REM-1.4.0-linux-x86_64.AppImage";
      sha256 = "sha256-rL6ebeURL3dcts53xIq5olHHnEQoK9rzIPdfXbu3H/c=";
    };
  };
  reverser_ai = {
    pname = "reverser_ai";
    version = "1d572da70479ea822875b9350135d7e3402f5557";
    src = fetchFromGitHub {
      owner = "mrphrazer";
      repo = "reverser_ai";
      rev = "1d572da70479ea822875b9350135d7e3402f5557";
      fetchSubmodules = false;
      sha256 = "sha256-07bh4ofudKLKYGgHySSK4mpDstuyybKFktIfp0s8V8g=";
    };
    date = "2026-05-20";
  };
  scrollmpris = {
    pname = "scrollmpris";
    version = "6f6261cb0ca405e5c1c53747e455f049dc95e867";
    src = fetchFromGitHub {
      owner = "BEST8OY";
      repo = "ScrollMPRIS";
      rev = "6f6261cb0ca405e5c1c53747e455f049dc95e867";
      fetchSubmodules = false;
      sha256 = "sha256-euT3rxUDaIkwZpEG2PRmyTUWIzDkG64L8L2QoJkmKwM=";
    };
    date = "2026-06-04";
  };
  sidr = {
    pname = "sidr";
    version = "v0.9.2";
    src = fetchFromGitHub {
      owner = "strozfriedberg";
      repo = "sidr";
      rev = "v0.9.2";
      fetchSubmodules = false;
      sha256 = "sha256-l6J+JJaFkFTDroMz6Ldnmq40OQGmEtL6l3ZFG6yk1GQ=";
    };
  };
  sstv = {
    pname = "sstv";
    version = "3e556eee8ad4c4425799cb652bac26ee58f8e113";
    src = fetchFromGitHub {
      owner = "colaclanth";
      repo = "sstv";
      rev = "3e556eee8ad4c4425799cb652bac26ee58f8e113";
      fetchSubmodules = false;
      sha256 = "sha256-s+G3MUVxEL/CwLaLk2nFcTFfRqq4Hrbj6qa/GhhzFMc=";
    };
    date = "2019-11-04";
  };
  stremio-enhanced = {
    pname = "stremio-enhanced";
    version = "1.2.0";
    src = fetchurl {
      url = "https://github.com/REVENGE977/stremio-enhanced/releases/download/v1.2.0/Stremio.Enhanced-1.2.0.AppImage";
      sha256 = "sha256-a+knxg/rd5Ied4RVK8Gg7xeFElovJab0gqxpjs11fAU=";
    };
  };
  trakt-scrobbler = {
    pname = "trakt-scrobbler";
    version = "v1.9.0b1";
    src = fetchFromGitHub {
      owner = "iamkroot";
      repo = "trakt-scrobbler";
      rev = "v1.9.0b1";
      fetchSubmodules = false;
      sha256 = "sha256-ylgCDWmcZzz6mMBpEAj16jK1loTxQJmk9G/3Hnp9WuI=";
    };
  };
  volatility-toolkit = {
    pname = "volatility-toolkit";
    version = "v2.1.1";
    src = fetchFromGitHub {
      owner = "gl0bal01";
      repo = "volatility-toolkit";
      rev = "v2.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-2HdfpF1DCn95HsArcvAeuWh5FNwjj9LxwJ/nlosHBmk=";
    };
  };
}
