# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  angr-management = {
    pname = "angr-management";
    version = "v9.3.3";
    src = fetchurl {
      url = "https://github.com/angr/angr-management/releases/download/v9.3.3/angr-management-v9.3.3-x86_64.AppImage";
      sha256 = "sha256-831I6hqwMMQqvil8savtRJrgzVv3oKXlfHur1jzMAs8=";
    };
  };
}
